import {
  LayoutDashboard,
  UserPlus,
  Users,
  Building,
  BookOpen,
  UserCog,
  Bus,
  CheckCircle,
  LayoutGrid,
  Bell,
  Bed,
  BarChart3,
  Shield,
} from "lucide-react";
import { FaMoneyBill } from "react-icons/fa";

export const sidebarItems = [
  { icon: LayoutDashboard, text: "Dashboard", route: "", active: true },
  { icon: Users, text: "Students", route: "/students" },
  {
    icon: FaMoneyBill,
    text: "Fee Management",
    route: "/fee",
    permission: "view:fee",
  },
  { icon: Bell, text: "Notifications", route: "/notifications" },
  {
    icon: BookOpen,
    text: "Certificates",
    route: "/certificate",
    permission: "view:certificates",
  },
  { icon: Building, text: "Departments", route: "/departments" },
  { icon: LayoutGrid, text: "Manage Classes", route: "/batches" },
  {
    icon: CheckCircle,
    text: "Due Management",
    route: "/dues",
    permission: "view:due",
  },
  {
    icon: UserPlus,
    text: "Admissions",
    route: "/admissions",
    alert: true,
    permission: "view:admissions",
  },
  { icon: Bus, text: "College Bus", route: "/bus", alert: true },
  { icon: Bed, text: "Hostel", route: "/hostel" },
  { icon: BarChart3, text: "Analytics", route: "/analytics", adminOnly: true },
  { icon: Shield, text: "Audit Logs", route: "/audit-logs", adminOnly: true },
  // { icon: GraduationCap, text: "Faculty", route: "/faculty" },
  // { icon: BookCopy, text: "Classes", route: "/classes" },
  {
    icon: UserCog,
    text: "Staff & Roles",
    route: "/staff-roles",
    adminOnly: true,
  },
];
